# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches: 
    - master
    - development
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts/erbium
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Rush
      run: npm install --global @microsoft/rush
    - name: Install dependencies
      run: rush install
    - name: Build projects
      run: rush build
    - name: Run tests
      run: rush test
